version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
    ports:
      - 5432:5432
    networks:
      - demo_kcs_net

  srvwildfly:
    image: myapp
    container_name: srvwildfly
    hostname: srvwildfly
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net
  
  srvapi:
    image: httpd:alpine
    container_name: srvapi
    ports:
      - 8880:8880
    depends_on:
      - srvwildfly
    networks:
      - demo_kcs_net
    volumes:
      - ./my2-httpd.conf:/usr/local/apache2/conf/httpd.conf

networks:
  demo_kcs_net: